spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_system_stock?serverTimezone=UTC
    username: root
    password: 123loquendero
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
   
